# Generated by Django 5.0.1 on 2024-05-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lastImage',
            field=models.ImageField(blank=True, default='/placeholder.jpg', max_length=300, null=True, upload_to=''),
        ),
    ]
