# Generated by Django 5.0.1 on 2024-05-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_alter_product_galary_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, default='https://detroit-watch.s3.eu-north-1.amazonaws.com/placeholder.jpg', max_length=300, null=True),
        ),
    ]
