# Generated by Django 5.0.1 on 2024-05-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='https://detroit-watch.s3.eu-north-1.amazonaws.com/placeholder.jpg', max_length=300, null=True, upload_to=''),
        ),
    ]
